#!/bin/bash

#Get directory in which the script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#Get interface used to connect to the internet
IF=$(bash "$DIR/internet_interface")

#Calculate delta of downloaded bytes in 1 second duration
RXB=$(</sys/class/net/$IF/statistics/rx_bytes)
sleep 1
RXBN=$(</sys/class/net/$IF/statistics/rx_bytes)
RXDIF=$(echo $((RXBN - RXB)) )

echo -e "$((RXDIF / 1024))" #Unit is KiB