#!/bin/zsh

#This is made for .conkyrc, not normal usage
#It divides the ping by 50 for the logarithmic scale

IP="8.8.8.8"

PING=$(/bin/ping $IP -c 1 -W 3)

if [[ $? != 0 ]] ; then
    echo 0;
else
    PING=$(echo $PING | grep "time=" | sed -ru 's/.*time=//;s/ms.*//')
    echo $(($PING / 50))
fi