#!/bin/bash

update_ping() {
    if [[ $1 != "" ]] ; then
        IP=$1
    else
        IP="8.8.8.8"
    fi

    while [[ $(ps -C tmux | wc -l) > 1 ]] ; do
        PING=$(/bin/ping $IP -c 1 -W 3)

        if [[ $? != 0 ]] ; then
            tmux setenv -g TMUX_PING "DOWN";
        else
            PING=$(echo $PING | sed -ru 's/.*time=//;s/ms.*/ms/')
            echo $PING
            tmux setenv -g TMUX_PING "$PING";
        fi

        sleep 0.5
    done
}

calculate() {
    if [[ $NET_CALCING == "true" ]] ; then
        return
    else
        DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

        while [[ $(ps -C tmux | wc -l) > 1 ]] ; do
            #Get interface used to connect to the internet
            IF=$(awk 'NR==3 {print $1}' /proc/net/route)

            #Calculate delta of downloaded bytes in 1 second duration
            TXB=$(</sys/class/net/$IF/statistics/tx_bytes)
            RXB=$(</sys/class/net/$IF/statistics/rx_bytes)
            sleep 1
            TXBN=$(</sys/class/net/$IF/statistics/tx_bytes)
            RXBN=$(</sys/class/net/$IF/statistics/rx_bytes)

            tmux setenv -g TMUX_UPSPEED "$(((TXBN - TXB) / 1024))" #Unit is KiB
            tmux setenv -g TMUX_DOWNSPEED "$(((RXBN - RXB) / 1024))" #Unit is KiB
        done
    fi
}

#Do not launch multiple copies
if [[ $(ps -C tmux_network_usage | wc -l) > 1 ]] ; then
    update_ping 8.8.8.8 &
    calculate
fi