#!/bin/bash

#Get directory in which the script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#Get interface used to connect to the internet
IF=$(bash "$DIR/internet_interface")

#Calculate delta of uploaded bytes in 1 second duration
TXB=$(</sys/class/net/$IF/statistics/tx_bytes)
sleep 1
TXBN=$(</sys/class/net/$IF/statistics/tx_bytes)
TXDIF=$(echo $((TXBN - TXB)) )

echo -e "$((TXDIF / 1024))" #Unit is KiB